export {default as Login } from './Login/Login'
export {default as Chat} from './Chat/Chat'
export {default as MainPage} from './MainPage/MainPage'
export {default as Header} from './Header/Header' 
export {default as NewChannel} from './Channel/NewChannel'
export {default as Profile} from './Profile/Profile'
